export const PHOTOBOOTH_CAMERA_SNAPPED = "PHOTO_BOOTH_CAMERA#SNAPPED";
export const PHOTOBOOTH_AVAILABLE_CAMERAS_UPDATED = "PHOTO_BOOTH_CAMERA#AVAILABLE_CAMERAS_UPDATED";
export const PHOTOBOOTH_CAMERA_SINGLE_SNAPPED = "PHOTO_BOOTH_CAMERA#SINGLE_SNAPPED";