export const PHOTOBOOTH_CAMERA_SNAPPED = "PHOTOBOOTH_CAMERA#SNAPPED";
export const PHOTOBOOTH_AVAILABLE_CAMERAS_UPDATED = "PHOTOBOOTH_CAMERA#AVAILABLE_CAMERAS_UPDATED";
export const PHOTOBOOTH_CAMERA_SINGLE_SNAPPED = "PHOTOBOOH_CAMERA#SINGLE_SNAPPED";